
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"khairul",
      "password":"1234"

}

###

POST http://localhost:3000/register
Content-Type: application/json

{
      "username":"khairul",
      "password":"1234",
      "name":"Khairul",
      "email":"khairul0425@gmail.com"

}

###

GET http://localhost:3000

###

GET http://localhost:3000/bruh